### PR TITLE
Add basic UI to OOP Library

### PR DESCRIPTION
**Pull request by sharon-odhiambo**
- In this PR I added the UI to the OOP School Library allowing the user to see all the options, select their preferred option and enter the required input. The ui prompts the user with required input and gives the data.

**Below** are the Highlights

- Add methods for:

1. Listing all books
2. Listing all people
3. Creating a book
4. Creating a person, student or teacher
5. Creating a rental
6. Listing all rentals
7. Exiting the app

- Present the user with the options
- Loop through the options and return the user's selected option
- Ensure no linter errors

**Cheers and Happy Reviewing!**

### CODE REVIEW

**Review by Deepakdanger — CHANGES_REQUESTED** [review]
Hi @sharon-odhiambo , 

Good job so far! 👏
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight :100: 
- No linter error :heavy_check_mark: 
- Website looks professional :+1: 

## Required Changes ♻️
- [ ] While creating student and teacher ,i am getting this error , Kindly resolve it, it seems this error is (wrong no.of parameters in initialize).

Screenshot from 2022-10-07 20-53-07
Screenshot from 2022-10-07 20-52-44


- [ ]  kindly check the rental creation before asking for the next review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sharon-odhiambo** [comment]
Hi @Deepakdanger , thank you for the review. I have implemented the changes.

**Review by zainsadaqat — APPROVED** [review]
# APPROVED!!!! 🎉 🎉 🎉 🎉 🎉 🎉
## Hey @sharon-odhiambo  😊 😃 

#### Great Job 😄 👏 You've done it. Your project is complete!  There is nothing else to say other than... it's time to merge it 👍🏻 ✅ 

# Congratulations!!! 🎉 🥳 👏 🙌 🎊 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sharon-odhiambo** [comment]
Hi @zainsadaqat, thank you!

**Pull request merged**
