### PR TITLE
Preserve data

### PR DESCRIPTION
**Pull request by sharon-odhiambo**
- In this PR we preserved all the data app and uploaded it on app start. 
- Preserve books, people and rentals data on exit in json files
- Load data from storage and upload it when starting the app
- Ensure no linter errors
- Maintain the correct GitFlow

NOTE: Currently there are no errors on our local version but the upstream one shows errors.
Screenshot (59)

**Cheers and Happy Reviewing!**

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Invalid Code Review Request ❌

Hi @sharon-odhiambo, This is @sja-thedude your code reviewer.

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

You have submitted a project, that doesn't pass all linter checks. Make sure all have blue tick.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by sharon-odhiambo** [comment]
Hello @sja-thedude , thank you for the review. We have indicated on the PR that the linters are passing on our local machines and added a screenshot. Could you please guide on the way forward?

**Comment by sja-thedude** [comment]
> Hello @sja-thedude , thank you for the review. We have indicated on the PR that the linters are passing on our local machines and added a screenshot. Could you please guide on the way forward?
> 
> 

Have you tried deleting all the linters files and pasting them again? If yes and still the error persists you could ask for another review..

**Comment by sharon-odhiambo** [comment]
Hello @sja-thedude . Yes we havee. Thank you.

**Review by VICTOR-CHUKWU — APPROVED** [review]
Hi @sharon-odhiambo  and @businesskaniki , 
# STATUS: APPROVED! 🥇 💯 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- [ ] All linters passed

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by sharon-odhiambo** [comment]
Hi @VICTOR-CHUKWU , thank you for the review.

**Pull request merged**
